/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Avatar.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Avatar({ animation, ...props }) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/Avatar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)


  useEffect(() => {

    const idle = actions['NlaTrack_Armature'];
    const run = actions['NlaTrack.001_Armature'];

    if (!run || !idle) return


    idle.play();
    run.play().setEffectiveTimeScale(1.3);

    if (animation === "run") {
      // eslint-disable-next-line react-hooks/immutability
      run.enabled = true;
      run.reset().fadeIn(0.2);
      idle.fadeOut(0.2);
    } else {
       
      idle.enabled = true;
      idle.reset().fadeIn(0.2);
      run.fadeOut(0.2)
    }
  }, [animation, actions])

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      material.roughness = 0.5;
      material.metalness = 0;
      material.needsUpdate = true;
    });

  }, [materials])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Root} />
          <skinnedMesh name="tripo_node_909a5ed3-7bd8-47ab-ba9e-cb775859e14b" geometry={nodes['tripo_node_909a5ed3-7bd8-47ab-ba9e-cb775859e14b'].geometry} material={materials['tripo_mat_909a5ed3-7bd8-47ab-ba9e-cb775859e14b']} skeleton={nodes['tripo_node_909a5ed3-7bd8-47ab-ba9e-cb775859e14b'].skeleton} castShadow />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Avatar.glb')
